### ISSUE TITLE
Add support for Hugo markdown

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/gdscript-docs-maker#33]
Compared to the normal markdown output, for hugo, you need:

- No h1 title, hugo templates generally handle that
- Hugo has its own shortcodes, e.g. for code blocks and code highlighting.
- A header as json, toml, or yaml. For the website, we only use toml, but we can easily support other markups by using file templates:

```toml
+++
title = "{title}"
description = {decsription}
author = "{author}"
date = "{date}"
+++
```

For date formatting:

```py
"{:%Y-%m-%d %H:%M:%S}".format(datetime.datetime())
```
